/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-01-27 00:24:00 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@123.207.28.107/moshi -t account -t account_l -t account_m -t account_role -t account_role_l -t account_role_m -t account_role_t -t account_t -t application -t application_l -t application_m -t application_t -t article -t article_comment -t article_comment_l -t article_comment_m -t article_comment_t -t article_l -t article_m -t article_t -t audio -t audio_l -t audio_m -t audio_t -t auth_code -t auth_code_l -t auth_code_m -t auth_code_t -t course -t course_l -t course_m -t course_t -t issue -t issue_comment -t issue_comment_l -t issue_comment_m -t issue_comment_t -t issue_l -t issue_m -t issue_t -t paragraph -t paragraph_comment -t paragraph_comment_l -t paragraph_comment_m -t paragraph_comment_t -t paragraph_l -t paragraph_m -t paragraph_t -t permission -t permission_l -t permission_m -t permission_t -t preset_text -t preset_text_l -t preset_text_m -t preset_text_t -t role -t role_l -t role_m -t role_permission -t role_permission_l -t role_permission_m -t role_permission_t -t role_t -t section -t section_l -t section_m -t section_t -t session -t session_l -t session_m -t session_t -t video -t video_l -t video_m -t video_t -s moshi
 *
 */


export interface IAccount {
    id: number;
    nickName: string;
    password: string;
    email: string;
    phone?: string;
    avatar: string;
    realName?: string;
    identityNumber?: string;
    age?: number;
    company?: string;
    position?: string;
    personalProfile?: string;
    sex?: string;
    birthday?: number;
    education?: string;
    profession?: string;
    createAt: number;
    status: number;

}

export interface IAccountL {
    id: number;
    nickName: string;
    password: string;
    email: string;
    phone?: string;
    avatar: string;
    realName?: string;
    identityNumber?: string;
    age?: number;
    company?: string;
    position?: string;
    personalProfile?: string;
    sex?: string;
    birthday?: number;
    education?: string;
    profession?: string;
    createAt: number;
    status: number;

}

export interface IAccountM {
    id: number;
    nickName: string;
    password: string;
    email: string;
    phone?: string;
    avatar: string;
    realName?: string;
    identityNumber?: string;
    age?: number;
    company?: string;
    position?: string;
    personalProfile?: string;
    sex?: string;
    birthday?: number;
    education?: string;
    profession?: string;
    createAt: number;
    status: number;

}

export interface IAccountRole {
    accountId: number;
    roleId: number;

}

export interface IAccountRoleL {
    accountId: number;
    roleId: number;

}

export interface IAccountRoleM {
    accountId: number;
    roleId: number;

}

export interface IAccountRoleT {
    accountId: number;
    roleId: number;

}

export interface IAccountT {
    id: number;
    nickName: string;
    password: string;
    email: string;
    phone?: string;
    avatar: string;
    realName?: string;
    identityNumber?: string;
    age?: number;
    company?: string;
    position?: string;
    personalProfile?: string;
    sex?: string;
    birthday?: number;
    education?: string;
    profession?: string;
    createAt: number;
    status: number;

}

export interface IApplication {
    id: number;
    accountId: number;
    category: number;
    title: string;
    content: string;
    createAt: number;
    status: number;
    reply?: string;
    refId: number;

}

export interface IApplicationL {
    id: number;
    accountId: number;
    category: number;
    title: string;
    content: string;
    createAt: number;
    status: number;
    reply?: string;
    refId: number;

}

export interface IApplicationM {
    id: number;
    accountId: number;
    category: number;
    title: string;
    content: string;
    createAt: number;
    status: number;
    reply?: string;
    refId: number;

}

export interface IApplicationT {
    id: number;
    accountId: number;
    category: number;
    title: string;
    content: string;
    createAt: number;
    status: number;
    reply?: string;
    refId: number;

}

export interface IArticle {
    id: number;
    courseId: number;
    title: string;
    content: string;
    publishAt?: number;
    createAt: number;
    status: number;
    audioId?: number;

}

export interface IArticleComment {
    id: number;
    articleId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface IArticleCommentL {
    id: number;
    articleId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface IArticleCommentM {
    id: number;
    articleId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface IArticleCommentT {
    id: number;
    articleId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface IArticleL {
    id: number;
    courseId: number;
    title: string;
    content: string;
    publishAt?: number;
    createAt: number;
    status: number;
    audioId?: number;

}

export interface IArticleM {
    id: number;
    courseId: number;
    title: string;
    content: string;
    publishAt?: number;
    createAt: number;
    status: number;
    audioId?: number;

}

export interface IArticleT {
    id: number;
    courseId: number;
    title: string;
    content: string;
    publishAt?: number;
    createAt: number;
    status: number;
    audioId?: number;

}

export interface IAudio {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;

}

export interface IAudioL {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;

}

export interface IAudioM {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;

}

export interface IAudioT {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;

}

export interface IAuthCode {
    id: string;
    accountId: number;
    expireAt: number;
    type: number;

}

export interface IAuthCodeL {
    id: string;
    accountId: number;
    expireAt: number;
    type: number;

}

export interface IAuthCodeM {
    id: string;
    accountId: number;
    expireAt: number;
    type: number;

}

export interface IAuthCodeT {
    id: string;
    accountId: number;
    expireAt: number;
    type: number;

}

export interface ICourse {
    id: number;
    accountId: number;
    name: string;
    introduce: string;
    introduceImage?: string;
    note?: string;
    createAt: number;
    publishAt?: number;
    buyerCount: number;
    courseType: number;
    price?: number;
    discountedPrice?: number;
    offerTo?: number;
    status: number;

}

export interface ICourseL {
    id: number;
    accountId: number;
    name: string;
    introduce: string;
    introduceImage?: string;
    note?: string;
    createAt: number;
    publishAt?: number;
    buyerCount: number;
    courseType: number;
    price?: number;
    discountedPrice?: number;
    offerTo?: number;
    status: number;

}

export interface ICourseM {
    id: number;
    accountId: number;
    name: string;
    introduce: string;
    introduceImage?: string;
    note?: string;
    createAt: number;
    publishAt?: number;
    buyerCount: number;
    courseType: number;
    price?: number;
    discountedPrice?: number;
    offerTo?: number;
    status: number;

}

export interface ICourseT {
    id: number;
    accountId: number;
    name: string;
    introduce: string;
    introduceImage?: string;
    note?: string;
    createAt: number;
    publishAt?: number;
    buyerCount: number;
    courseType: number;
    price?: number;
    discountedPrice?: number;
    offerTo?: number;
    status: number;

}

export interface IIssue {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    openAt: number;
    closerId?: number;
    closeAt?: number;
    status: number;

}

export interface IIssueComment {
    id: number;
    issueId: number;
    accountId: number;
    createAt: number;
    content: string;
    status: number;

}

export interface IIssueCommentL {
    id: number;
    issueId: number;
    accountId: number;
    createAt: number;
    content: string;
    status: number;

}

export interface IIssueCommentM {
    id: number;
    issueId: number;
    accountId: number;
    createAt: number;
    content: string;
    status: number;

}

export interface IIssueCommentT {
    id: number;
    issueId: number;
    accountId: number;
    createAt: number;
    content: string;
    status: number;

}

export interface IIssueL {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    openAt: number;
    closeAt?: number;
    status: number;

}

export interface IIssueM {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    openAt: number;
    closeAt?: number;
    status: number;

}

export interface IIssueT {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    openAt: number;
    closeAt?: number;
    status: number;

}

export interface IParagraph {
    id: number;
    sectionId: number;
    accountId: number;
    vedioId: number;
    content: string;
    createAt: number;
    status: number;

}

export interface IParagraphComment {
    id: number;
    paragraphId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface IParagraphCommentL {
    id: number;
    paragraphId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface IParagraphCommentM {
    id: number;
    paragraphId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface IParagraphCommentT {
    id: number;
    paragraphId: number;
    accountId: number;
    content: string;
    createAt: number;
    status: number;
    replyTo?: number;

}

export interface IParagraphL {
    id: number;
    sectionId: number;
    accountId: number;
    vedioId: number;
    content: string;
    createAt: number;
    status: number;

}

export interface IParagraphM {
    id: number;
    sectionId: number;
    accountId: number;
    vedioId: number;
    content: string;
    createAt: number;
    status: number;

}

export interface IParagraphT {
    id: number;
    sectionId: number;
    accountId: number;
    vedioId: number;
    content: string;
    createAt: number;
    status: number;

}

export interface IPermission {
    id: number;
    actionKey: string;
    controller: string;
    remark?: string;

}

export interface IPermissionL {
    id: number;
    actionKey: string;
    controller: string;
    remark?: string;

}

export interface IPermissionM {
    id: number;
    actionKey: string;
    controller: string;
    remark?: string;

}

export interface IPermissionT {
    id: number;
    actionKey: string;
    controller: string;
    remark?: string;

}

export interface IPresetText {
    key: string;
    value: string;

}

export interface IPresetTextL {
    key: string;
    value: string;

}

export interface IPresetTextM {
    key: string;
    value: string;

}

export interface IPresetTextT {
    key: string;
    value: string;

}

export interface IRole {
    id: number;
    name: string;
    createAt: number;

}

export interface IRoleL {
    id: number;
    name: string;
    createAt: number;

}

export interface IRoleM {
    id: number;
    name: string;
    createAt: number;

}

export interface IRolePermission {
    roleId: number;
    permissionId: number;

}

export interface IRolePermissionL {
    roleId: number;
    permissionId: number;

}

export interface IRolePermissionM {
    roleId: number;
    permissionId: number;

}

export interface IRolePermissionT {
    roleId: number;
    permissionId: number;

}

export interface IRoleT {
    id: number;
    name: string;
    createAt: number;

}

export interface ISection {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    createAt: number;
    status: number;

}

export interface ISectionL {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    createAt: number;
    status: number;

}

export interface ISectionM {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    createAt: number;
    status: number;

}

export interface ISectionT {
    id: number;
    courseId: number;
    accountId: number;
    title: string;
    createAt: number;
    status: number;

}

export interface ISession {
    id: string;
    accountId: number;
    expireAt: number;

}

export interface ISessionL {
    id: string;
    accountId: number;
    expireAt: number;

}

export interface ISessionM {
    id: string;
    accountId: number;
    expireAt: number;

}

export interface ISessionT {
    id: string;
    accountId: number;
    expireAt: number;

}

export interface IVideo {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;

}

export interface IVideoL {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;

}

export interface IVideoM {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;

}

export interface IVideoT {
    id: number;
    resource: string;
    recorder: string;
    accountId: number;
    status: number;

}
