/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-01-23 22:22:02 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@123.207.28.107/moshi -t account -t account_l -t account_m -t account_role -t account_role_l -t account_role_m -t account_role_t -t account_t -t application -t application_l -t application_m -t application_t -t article -t article_comment -t article_comment_l -t article_comment_m -t article_comment_t -t article_l -t article_m -t article_t -t audio -t audio_l -t audio_m -t audio_t -t auth_code -t auth_code_l -t auth_code_m -t auth_code_t -t course -t course_l -t course_m -t course_t -t issue -t issue_comment -t issue_comment_l -t issue_comment_m -t issue_comment_t -t issue_l -t issue_m -t issue_t -t paragraph -t paragraph_comment -t paragraph_comment_l -t paragraph_comment_m -t paragraph_comment_t -t paragraph_l -t paragraph_m -t paragraph_t -t permission -t permission_l -t permission_m -t permission_t -t preset_text -t preset_text_l -t preset_text_m -t preset_text_t -t role -t role_l -t role_m -t role_permission -t role_permission_l -t role_permission_m -t role_permission_t -t role_t -t section -t section_l -t section_m -t section_t -t session -t session_l -t session_m -t session_t -t video -t video_l -t video_m -t video_t -s moshi
 *
 */


export namespace accountFields {
    export type id = number;
    export type nickName = string;
    export type password = string;
    export type email = string;
    export type phone = string | null;
    export type avatar = string;
    export type realName = string | null;
    export type identityNumber = string | null;
    export type age = number | null;
    export type company = string | null;
    export type position = string | null;
    export type personalProfile = string | null;
    export type sex = string | null;
    export type birthday = number | null;
    export type education = string | null;
    export type profession = string | null;
    export type createAt = number;
    export type status = number;

}

export interface account {
    id: accountFields.id;
    nickName: accountFields.nickName;
    password: accountFields.password;
    email: accountFields.email;
    phone: accountFields.phone;
    avatar: accountFields.avatar;
    realName: accountFields.realName;
    identityNumber: accountFields.identityNumber;
    age: accountFields.age;
    company: accountFields.company;
    position: accountFields.position;
    personalProfile: accountFields.personalProfile;
    sex: accountFields.sex;
    birthday: accountFields.birthday;
    education: accountFields.education;
    profession: accountFields.profession;
    createAt: accountFields.createAt;
    status: accountFields.status;

}

export namespace account_lFields {
    export type id = number;
    export type nickName = string;
    export type password = string;
    export type email = string;
    export type phone = string | null;
    export type avatar = string;
    export type realName = string | null;
    export type identityNumber = string | null;
    export type age = number | null;
    export type company = string | null;
    export type position = string | null;
    export type personalProfile = string | null;
    export type sex = string | null;
    export type birthday = number | null;
    export type education = string | null;
    export type profession = string | null;
    export type createAt = number;
    export type status = number;

}

export interface account_l {
    id: account_lFields.id;
    nickName: account_lFields.nickName;
    password: account_lFields.password;
    email: account_lFields.email;
    phone: account_lFields.phone;
    avatar: account_lFields.avatar;
    realName: account_lFields.realName;
    identityNumber: account_lFields.identityNumber;
    age: account_lFields.age;
    company: account_lFields.company;
    position: account_lFields.position;
    personalProfile: account_lFields.personalProfile;
    sex: account_lFields.sex;
    birthday: account_lFields.birthday;
    education: account_lFields.education;
    profession: account_lFields.profession;
    createAt: account_lFields.createAt;
    status: account_lFields.status;

}

export namespace account_mFields {
    export type id = number;
    export type nickName = string;
    export type password = string;
    export type email = string;
    export type phone = string | null;
    export type avatar = string;
    export type realName = string | null;
    export type identityNumber = string | null;
    export type age = number | null;
    export type company = string | null;
    export type position = string | null;
    export type personalProfile = string | null;
    export type sex = string | null;
    export type birthday = number | null;
    export type education = string | null;
    export type profession = string | null;
    export type createAt = number;
    export type status = number;

}

export interface account_m {
    id: account_mFields.id;
    nickName: account_mFields.nickName;
    password: account_mFields.password;
    email: account_mFields.email;
    phone: account_mFields.phone;
    avatar: account_mFields.avatar;
    realName: account_mFields.realName;
    identityNumber: account_mFields.identityNumber;
    age: account_mFields.age;
    company: account_mFields.company;
    position: account_mFields.position;
    personalProfile: account_mFields.personalProfile;
    sex: account_mFields.sex;
    birthday: account_mFields.birthday;
    education: account_mFields.education;
    profession: account_mFields.profession;
    createAt: account_mFields.createAt;
    status: account_mFields.status;

}

export namespace account_roleFields {
    export type accountId = number;
    export type roleId = number;

}

export interface account_role {
    accountId: account_roleFields.accountId;
    roleId: account_roleFields.roleId;

}

export namespace account_role_lFields {
    export type accountId = number;
    export type roleId = number;

}

export interface account_role_l {
    accountId: account_role_lFields.accountId;
    roleId: account_role_lFields.roleId;

}

export namespace account_role_mFields {
    export type accountId = number;
    export type roleId = number;

}

export interface account_role_m {
    accountId: account_role_mFields.accountId;
    roleId: account_role_mFields.roleId;

}

export namespace account_role_tFields {
    export type accountId = number;
    export type roleId = number;

}

export interface account_role_t {
    accountId: account_role_tFields.accountId;
    roleId: account_role_tFields.roleId;

}

export namespace account_tFields {
    export type id = number;
    export type nickName = string;
    export type password = string;
    export type email = string;
    export type phone = string | null;
    export type avatar = string;
    export type realName = string | null;
    export type identityNumber = string | null;
    export type age = number | null;
    export type company = string | null;
    export type position = string | null;
    export type personalProfile = string | null;
    export type sex = string | null;
    export type birthday = number | null;
    export type education = string | null;
    export type profession = string | null;
    export type createAt = number;
    export type status = number;

}

export interface account_t {
    id: account_tFields.id;
    nickName: account_tFields.nickName;
    password: account_tFields.password;
    email: account_tFields.email;
    phone: account_tFields.phone;
    avatar: account_tFields.avatar;
    realName: account_tFields.realName;
    identityNumber: account_tFields.identityNumber;
    age: account_tFields.age;
    company: account_tFields.company;
    position: account_tFields.position;
    personalProfile: account_tFields.personalProfile;
    sex: account_tFields.sex;
    birthday: account_tFields.birthday;
    education: account_tFields.education;
    profession: account_tFields.profession;
    createAt: account_tFields.createAt;
    status: account_tFields.status;

}

export namespace applicationFields {
    export type id = number;
    export type accountId = number;
    export type category = number;
    export type title = string;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type reply = string | null;
    export type refId = number;

}

export interface application {
    id: applicationFields.id;
    accountId: applicationFields.accountId;
    category: applicationFields.category;
    title: applicationFields.title;
    content: applicationFields.content;
    createAt: applicationFields.createAt;
    status: applicationFields.status;
    reply: applicationFields.reply;
    refId: applicationFields.refId;

}

export namespace application_lFields {
    export type id = number;
    export type accountId = number;
    export type category = number;
    export type title = string;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type reply = string | null;
    export type refId = number;

}

export interface application_l {
    id: application_lFields.id;
    accountId: application_lFields.accountId;
    category: application_lFields.category;
    title: application_lFields.title;
    content: application_lFields.content;
    createAt: application_lFields.createAt;
    status: application_lFields.status;
    reply: application_lFields.reply;
    refId: application_lFields.refId;

}

export namespace application_mFields {
    export type id = number;
    export type accountId = number;
    export type category = number;
    export type title = string;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type reply = string | null;
    export type refId = number;

}

export interface application_m {
    id: application_mFields.id;
    accountId: application_mFields.accountId;
    category: application_mFields.category;
    title: application_mFields.title;
    content: application_mFields.content;
    createAt: application_mFields.createAt;
    status: application_mFields.status;
    reply: application_mFields.reply;
    refId: application_mFields.refId;

}

export namespace application_tFields {
    export type id = number;
    export type accountId = number;
    export type category = number;
    export type title = string;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type reply = string | null;
    export type refId = number;

}

export interface application_t {
    id: application_tFields.id;
    accountId: application_tFields.accountId;
    category: application_tFields.category;
    title: application_tFields.title;
    content: application_tFields.content;
    createAt: application_tFields.createAt;
    status: application_tFields.status;
    reply: application_tFields.reply;
    refId: application_tFields.refId;

}

export namespace articleFields {
    export type id = number;
    export type accountId = number;
    export type title = string;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type audioId = number | null;

}

export interface article {
    id: articleFields.id;
    accountId: articleFields.accountId;
    title: articleFields.title;
    content: articleFields.content;
    createAt: articleFields.createAt;
    status: articleFields.status;
    audioId: articleFields.audioId;

}

export namespace article_commentFields {
    export type id = number;
    export type articleId = number;
    export type accountId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type replyTo = number | null;

}

export interface article_comment {
    id: article_commentFields.id;
    articleId: article_commentFields.articleId;
    accountId: article_commentFields.accountId;
    content: article_commentFields.content;
    createAt: article_commentFields.createAt;
    status: article_commentFields.status;
    replyTo: article_commentFields.replyTo;

}

export namespace article_comment_lFields {
    export type id = number;
    export type articleId = number;
    export type accountId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type replyTo = number | null;

}

export interface article_comment_l {
    id: article_comment_lFields.id;
    articleId: article_comment_lFields.articleId;
    accountId: article_comment_lFields.accountId;
    content: article_comment_lFields.content;
    createAt: article_comment_lFields.createAt;
    status: article_comment_lFields.status;
    replyTo: article_comment_lFields.replyTo;

}

export namespace article_comment_mFields {
    export type id = number;
    export type articleId = number;
    export type accountId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type replyTo = number | null;

}

export interface article_comment_m {
    id: article_comment_mFields.id;
    articleId: article_comment_mFields.articleId;
    accountId: article_comment_mFields.accountId;
    content: article_comment_mFields.content;
    createAt: article_comment_mFields.createAt;
    status: article_comment_mFields.status;
    replyTo: article_comment_mFields.replyTo;

}

export namespace article_comment_tFields {
    export type id = number;
    export type articleId = number;
    export type accountId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type replyTo = number | null;

}

export interface article_comment_t {
    id: article_comment_tFields.id;
    articleId: article_comment_tFields.articleId;
    accountId: article_comment_tFields.accountId;
    content: article_comment_tFields.content;
    createAt: article_comment_tFields.createAt;
    status: article_comment_tFields.status;
    replyTo: article_comment_tFields.replyTo;

}

export namespace article_lFields {
    export type id = number;
    export type accountId = number;
    export type title = string;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type audioId = number | null;

}

export interface article_l {
    id: article_lFields.id;
    accountId: article_lFields.accountId;
    title: article_lFields.title;
    content: article_lFields.content;
    createAt: article_lFields.createAt;
    status: article_lFields.status;
    audioId: article_lFields.audioId;

}

export namespace article_mFields {
    export type id = number;
    export type accountId = number;
    export type title = string;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type audioId = number | null;

}

export interface article_m {
    id: article_mFields.id;
    accountId: article_mFields.accountId;
    title: article_mFields.title;
    content: article_mFields.content;
    createAt: article_mFields.createAt;
    status: article_mFields.status;
    audioId: article_mFields.audioId;

}

export namespace article_tFields {
    export type id = number;
    export type accountId = number;
    export type title = string;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type audioId = number | null;

}

export interface article_t {
    id: article_tFields.id;
    accountId: article_tFields.accountId;
    title: article_tFields.title;
    content: article_tFields.content;
    createAt: article_tFields.createAt;
    status: article_tFields.status;
    audioId: article_tFields.audioId;

}

export namespace audioFields {
    export type id = number;
    export type resource = string;
    export type recorder = string;
    export type accountId = number;
    export type status = number;

}

export interface audio {
    id: audioFields.id;
    resource: audioFields.resource;
    recorder: audioFields.recorder;
    accountId: audioFields.accountId;
    status: audioFields.status;

}

export namespace audio_lFields {
    export type id = number;
    export type resource = string;
    export type recorder = string;
    export type accountId = number;
    export type status = number;

}

export interface audio_l {
    id: audio_lFields.id;
    resource: audio_lFields.resource;
    recorder: audio_lFields.recorder;
    accountId: audio_lFields.accountId;
    status: audio_lFields.status;

}

export namespace audio_mFields {
    export type id = number;
    export type resource = string;
    export type recorder = string;
    export type accountId = number;
    export type status = number;

}

export interface audio_m {
    id: audio_mFields.id;
    resource: audio_mFields.resource;
    recorder: audio_mFields.recorder;
    accountId: audio_mFields.accountId;
    status: audio_mFields.status;

}

export namespace audio_tFields {
    export type id = number;
    export type resource = string;
    export type recorder = string;
    export type accountId = number;
    export type status = number;

}

export interface audio_t {
    id: audio_tFields.id;
    resource: audio_tFields.resource;
    recorder: audio_tFields.recorder;
    accountId: audio_tFields.accountId;
    status: audio_tFields.status;

}

export namespace auth_codeFields {
    export type id = string;
    export type accountId = number;
    export type expireAt = number;
    export type type = number;

}

export interface auth_code {
    id: auth_codeFields.id;
    accountId: auth_codeFields.accountId;
    expireAt: auth_codeFields.expireAt;
    type: auth_codeFields.type;

}

export namespace auth_code_lFields {
    export type id = string;
    export type accountId = number;
    export type expireAt = number;
    export type type = number;

}

export interface auth_code_l {
    id: auth_code_lFields.id;
    accountId: auth_code_lFields.accountId;
    expireAt: auth_code_lFields.expireAt;
    type: auth_code_lFields.type;

}

export namespace auth_code_mFields {
    export type id = string;
    export type accountId = number;
    export type expireAt = number;
    export type type = number;

}

export interface auth_code_m {
    id: auth_code_mFields.id;
    accountId: auth_code_mFields.accountId;
    expireAt: auth_code_mFields.expireAt;
    type: auth_code_mFields.type;

}

export namespace auth_code_tFields {
    export type id = string;
    export type accountId = number;
    export type expireAt = number;
    export type type = number;

}

export interface auth_code_t {
    id: auth_code_tFields.id;
    accountId: auth_code_tFields.accountId;
    expireAt: auth_code_tFields.expireAt;
    type: auth_code_tFields.type;

}

export namespace courseFields {
    export type id = number;
    export type accountId = number;
    export type name = string;
    export type introduce = string;
    export type introduceImage = string | null;
    export type note = string | null;
    export type createAt = number;
    export type publishAt = number | null;
    export type buyerCount = number;
    export type courseType = number;
    export type price = number | null;
    export type discountedPrice = number | null;
    export type offerTo = number | null;
    export type status = number;

}

export interface course {
    id: courseFields.id;
    accountId: courseFields.accountId;
    name: courseFields.name;
    introduce: courseFields.introduce;
    introduceImage: courseFields.introduceImage;
    note: courseFields.note;
    createAt: courseFields.createAt;
    publishAt: courseFields.publishAt;
    buyerCount: courseFields.buyerCount;
    courseType: courseFields.courseType;
    price: courseFields.price;
    discountedPrice: courseFields.discountedPrice;
    offerTo: courseFields.offerTo;
    status: courseFields.status;

}

export namespace course_lFields {
    export type id = number;
    export type accountId = number;
    export type name = string;
    export type introduce = string;
    export type introduceImage = string | null;
    export type note = string | null;
    export type createAt = number;
    export type publishAt = number | null;
    export type buyerCount = number;
    export type courseType = number;
    export type price = number | null;
    export type discountedPrice = number | null;
    export type offerTo = number | null;
    export type status = number;

}

export interface course_l {
    id: course_lFields.id;
    accountId: course_lFields.accountId;
    name: course_lFields.name;
    introduce: course_lFields.introduce;
    introduceImage: course_lFields.introduceImage;
    note: course_lFields.note;
    createAt: course_lFields.createAt;
    publishAt: course_lFields.publishAt;
    buyerCount: course_lFields.buyerCount;
    courseType: course_lFields.courseType;
    price: course_lFields.price;
    discountedPrice: course_lFields.discountedPrice;
    offerTo: course_lFields.offerTo;
    status: course_lFields.status;

}

export namespace course_mFields {
    export type id = number;
    export type accountId = number;
    export type name = string;
    export type introduce = string;
    export type introduceImage = string | null;
    export type note = string | null;
    export type createAt = number;
    export type publishAt = number | null;
    export type buyerCount = number;
    export type courseType = number;
    export type price = number | null;
    export type discountedPrice = number | null;
    export type offerTo = number | null;
    export type status = number;

}

export interface course_m {
    id: course_mFields.id;
    accountId: course_mFields.accountId;
    name: course_mFields.name;
    introduce: course_mFields.introduce;
    introduceImage: course_mFields.introduceImage;
    note: course_mFields.note;
    createAt: course_mFields.createAt;
    publishAt: course_mFields.publishAt;
    buyerCount: course_mFields.buyerCount;
    courseType: course_mFields.courseType;
    price: course_mFields.price;
    discountedPrice: course_mFields.discountedPrice;
    offerTo: course_mFields.offerTo;
    status: course_mFields.status;

}

export namespace course_tFields {
    export type id = number;
    export type accountId = number;
    export type name = string;
    export type introduce = string;
    export type introduceImage = string | null;
    export type note = string | null;
    export type createAt = number;
    export type publishAt = number | null;
    export type buyerCount = number;
    export type courseType = number;
    export type price = number | null;
    export type discountedPrice = number | null;
    export type offerTo = number | null;
    export type status = number;

}

export interface course_t {
    id: course_tFields.id;
    accountId: course_tFields.accountId;
    name: course_tFields.name;
    introduce: course_tFields.introduce;
    introduceImage: course_tFields.introduceImage;
    note: course_tFields.note;
    createAt: course_tFields.createAt;
    publishAt: course_tFields.publishAt;
    buyerCount: course_tFields.buyerCount;
    courseType: course_tFields.courseType;
    price: course_tFields.price;
    discountedPrice: course_tFields.discountedPrice;
    offerTo: course_tFields.offerTo;
    status: course_tFields.status;

}

export namespace issueFields {
    export type id = number;
    export type courseId = number;
    export type accountId = number;
    export type title = string;
    export type createAt = number;
    export type status = number;

}

export interface issue {
    id: issueFields.id;
    courseId: issueFields.courseId;
    accountId: issueFields.accountId;
    title: issueFields.title;
    createAt: issueFields.createAt;
    status: issueFields.status;

}

export namespace issue_commentFields {
    export type id = number;
    export type issueId = number;
    export type accountId = number;
    export type createAt = number;
    export type content = string;
    export type status = number;

}

export interface issue_comment {
    id: issue_commentFields.id;
    issueId: issue_commentFields.issueId;
    accountId: issue_commentFields.accountId;
    createAt: issue_commentFields.createAt;
    content: issue_commentFields.content;
    status: issue_commentFields.status;

}

export namespace issue_comment_lFields {
    export type id = number;
    export type issueId = number;
    export type accountId = number;
    export type createAt = number;
    export type content = string;
    export type status = number;

}

export interface issue_comment_l {
    id: issue_comment_lFields.id;
    issueId: issue_comment_lFields.issueId;
    accountId: issue_comment_lFields.accountId;
    createAt: issue_comment_lFields.createAt;
    content: issue_comment_lFields.content;
    status: issue_comment_lFields.status;

}

export namespace issue_comment_mFields {
    export type id = number;
    export type issueId = number;
    export type accountId = number;
    export type createAt = number;
    export type content = string;
    export type status = number;

}

export interface issue_comment_m {
    id: issue_comment_mFields.id;
    issueId: issue_comment_mFields.issueId;
    accountId: issue_comment_mFields.accountId;
    createAt: issue_comment_mFields.createAt;
    content: issue_comment_mFields.content;
    status: issue_comment_mFields.status;

}

export namespace issue_comment_tFields {
    export type id = number;
    export type issueId = number;
    export type accountId = number;
    export type createAt = number;
    export type content = string;
    export type status = number;

}

export interface issue_comment_t {
    id: issue_comment_tFields.id;
    issueId: issue_comment_tFields.issueId;
    accountId: issue_comment_tFields.accountId;
    createAt: issue_comment_tFields.createAt;
    content: issue_comment_tFields.content;
    status: issue_comment_tFields.status;

}

export namespace issue_lFields {
    export type id = number;
    export type courseId = number;
    export type accountId = number;
    export type title = string;
    export type createAt = number;
    export type status = number;

}

export interface issue_l {
    id: issue_lFields.id;
    courseId: issue_lFields.courseId;
    accountId: issue_lFields.accountId;
    title: issue_lFields.title;
    createAt: issue_lFields.createAt;
    status: issue_lFields.status;

}

export namespace issue_mFields {
    export type id = number;
    export type courseId = number;
    export type accountId = number;
    export type title = string;
    export type createAt = number;
    export type status = number;

}

export interface issue_m {
    id: issue_mFields.id;
    courseId: issue_mFields.courseId;
    accountId: issue_mFields.accountId;
    title: issue_mFields.title;
    createAt: issue_mFields.createAt;
    status: issue_mFields.status;

}

export namespace issue_tFields {
    export type id = number;
    export type courseId = number;
    export type accountId = number;
    export type title = string;
    export type createAt = number;
    export type status = number;

}

export interface issue_t {
    id: issue_tFields.id;
    courseId: issue_tFields.courseId;
    accountId: issue_tFields.accountId;
    title: issue_tFields.title;
    createAt: issue_tFields.createAt;
    status: issue_tFields.status;

}

export namespace paragraphFields {
    export type id = number;
    export type sectionId = number;
    export type accountId = number;
    export type vedioId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;

}

export interface paragraph {
    id: paragraphFields.id;
    sectionId: paragraphFields.sectionId;
    accountId: paragraphFields.accountId;
    vedioId: paragraphFields.vedioId;
    content: paragraphFields.content;
    createAt: paragraphFields.createAt;
    status: paragraphFields.status;

}

export namespace paragraph_commentFields {
    export type id = number;
    export type paragraphId = number;
    export type accountId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type replyTo = number | null;

}

export interface paragraph_comment {
    id: paragraph_commentFields.id;
    paragraphId: paragraph_commentFields.paragraphId;
    accountId: paragraph_commentFields.accountId;
    content: paragraph_commentFields.content;
    createAt: paragraph_commentFields.createAt;
    status: paragraph_commentFields.status;
    replyTo: paragraph_commentFields.replyTo;

}

export namespace paragraph_comment_lFields {
    export type id = number;
    export type paragraphId = number;
    export type accountId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type replyTo = number | null;

}

export interface paragraph_comment_l {
    id: paragraph_comment_lFields.id;
    paragraphId: paragraph_comment_lFields.paragraphId;
    accountId: paragraph_comment_lFields.accountId;
    content: paragraph_comment_lFields.content;
    createAt: paragraph_comment_lFields.createAt;
    status: paragraph_comment_lFields.status;
    replyTo: paragraph_comment_lFields.replyTo;

}

export namespace paragraph_comment_mFields {
    export type id = number;
    export type paragraphId = number;
    export type accountId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type replyTo = number | null;

}

export interface paragraph_comment_m {
    id: paragraph_comment_mFields.id;
    paragraphId: paragraph_comment_mFields.paragraphId;
    accountId: paragraph_comment_mFields.accountId;
    content: paragraph_comment_mFields.content;
    createAt: paragraph_comment_mFields.createAt;
    status: paragraph_comment_mFields.status;
    replyTo: paragraph_comment_mFields.replyTo;

}

export namespace paragraph_comment_tFields {
    export type id = number;
    export type paragraphId = number;
    export type accountId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;
    export type replyTo = number | null;

}

export interface paragraph_comment_t {
    id: paragraph_comment_tFields.id;
    paragraphId: paragraph_comment_tFields.paragraphId;
    accountId: paragraph_comment_tFields.accountId;
    content: paragraph_comment_tFields.content;
    createAt: paragraph_comment_tFields.createAt;
    status: paragraph_comment_tFields.status;
    replyTo: paragraph_comment_tFields.replyTo;

}

export namespace paragraph_lFields {
    export type id = number;
    export type sectionId = number;
    export type accountId = number;
    export type vedioId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;

}

export interface paragraph_l {
    id: paragraph_lFields.id;
    sectionId: paragraph_lFields.sectionId;
    accountId: paragraph_lFields.accountId;
    vedioId: paragraph_lFields.vedioId;
    content: paragraph_lFields.content;
    createAt: paragraph_lFields.createAt;
    status: paragraph_lFields.status;

}

export namespace paragraph_mFields {
    export type id = number;
    export type sectionId = number;
    export type accountId = number;
    export type vedioId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;

}

export interface paragraph_m {
    id: paragraph_mFields.id;
    sectionId: paragraph_mFields.sectionId;
    accountId: paragraph_mFields.accountId;
    vedioId: paragraph_mFields.vedioId;
    content: paragraph_mFields.content;
    createAt: paragraph_mFields.createAt;
    status: paragraph_mFields.status;

}

export namespace paragraph_tFields {
    export type id = number;
    export type sectionId = number;
    export type accountId = number;
    export type vedioId = number;
    export type content = string;
    export type createAt = number;
    export type status = number;

}

export interface paragraph_t {
    id: paragraph_tFields.id;
    sectionId: paragraph_tFields.sectionId;
    accountId: paragraph_tFields.accountId;
    vedioId: paragraph_tFields.vedioId;
    content: paragraph_tFields.content;
    createAt: paragraph_tFields.createAt;
    status: paragraph_tFields.status;

}

export namespace permissionFields {
    export type id = number;
    export type actionKey = string;
    export type controller = string;
    export type remark = string | null;

}

export interface permission {
    id: permissionFields.id;
    actionKey: permissionFields.actionKey;
    controller: permissionFields.controller;
    remark: permissionFields.remark;

}

export namespace permission_lFields {
    export type id = number;
    export type actionKey = string;
    export type controller = string;
    export type remark = string | null;

}

export interface permission_l {
    id: permission_lFields.id;
    actionKey: permission_lFields.actionKey;
    controller: permission_lFields.controller;
    remark: permission_lFields.remark;

}

export namespace permission_mFields {
    export type id = number;
    export type actionKey = string;
    export type controller = string;
    export type remark = string | null;

}

export interface permission_m {
    id: permission_mFields.id;
    actionKey: permission_mFields.actionKey;
    controller: permission_mFields.controller;
    remark: permission_mFields.remark;

}

export namespace permission_tFields {
    export type id = number;
    export type actionKey = string;
    export type controller = string;
    export type remark = string | null;

}

export interface permission_t {
    id: permission_tFields.id;
    actionKey: permission_tFields.actionKey;
    controller: permission_tFields.controller;
    remark: permission_tFields.remark;

}

export namespace preset_textFields {
    export type key = string;
    export type value = string;

}

export interface preset_text {
    key: preset_textFields.key;
    value: preset_textFields.value;

}

export namespace preset_text_lFields {
    export type key = string;
    export type value = string;

}

export interface preset_text_l {
    key: preset_text_lFields.key;
    value: preset_text_lFields.value;

}

export namespace preset_text_mFields {
    export type key = string;
    export type value = string;

}

export interface preset_text_m {
    key: preset_text_mFields.key;
    value: preset_text_mFields.value;

}

export namespace preset_text_tFields {
    export type key = string;
    export type value = string;

}

export interface preset_text_t {
    key: preset_text_tFields.key;
    value: preset_text_tFields.value;

}

export namespace roleFields {
    export type id = number;
    export type name = string;
    export type createAt = number;

}

export interface role {
    id: roleFields.id;
    name: roleFields.name;
    createAt: roleFields.createAt;

}

export namespace role_lFields {
    export type id = number;
    export type name = string;
    export type createAt = number;

}

export interface role_l {
    id: role_lFields.id;
    name: role_lFields.name;
    createAt: role_lFields.createAt;

}

export namespace role_mFields {
    export type id = number;
    export type name = string;
    export type createAt = number;

}

export interface role_m {
    id: role_mFields.id;
    name: role_mFields.name;
    createAt: role_mFields.createAt;

}

export namespace role_permissionFields {
    export type roleId = number;
    export type permissionId = number;

}

export interface role_permission {
    roleId: role_permissionFields.roleId;
    permissionId: role_permissionFields.permissionId;

}

export namespace role_permission_lFields {
    export type roleId = number;
    export type permissionId = number;

}

export interface role_permission_l {
    roleId: role_permission_lFields.roleId;
    permissionId: role_permission_lFields.permissionId;

}

export namespace role_permission_mFields {
    export type roleId = number;
    export type permissionId = number;

}

export interface role_permission_m {
    roleId: role_permission_mFields.roleId;
    permissionId: role_permission_mFields.permissionId;

}

export namespace role_permission_tFields {
    export type roleId = number;
    export type permissionId = number;

}

export interface role_permission_t {
    roleId: role_permission_tFields.roleId;
    permissionId: role_permission_tFields.permissionId;

}

export namespace role_tFields {
    export type id = number;
    export type name = string;
    export type createAt = number;

}

export interface role_t {
    id: role_tFields.id;
    name: role_tFields.name;
    createAt: role_tFields.createAt;

}

export namespace sectionFields {
    export type id = number;
    export type courseId = number;
    export type accountId = number;
    export type title = string;
    export type createAt = number;
    export type status = number;

}

export interface section {
    id: sectionFields.id;
    courseId: sectionFields.courseId;
    accountId: sectionFields.accountId;
    title: sectionFields.title;
    createAt: sectionFields.createAt;
    status: sectionFields.status;

}

export namespace section_lFields {
    export type id = number;
    export type courseId = number;
    export type accountId = number;
    export type title = string;
    export type createAt = number;
    export type status = number;

}

export interface section_l {
    id: section_lFields.id;
    courseId: section_lFields.courseId;
    accountId: section_lFields.accountId;
    title: section_lFields.title;
    createAt: section_lFields.createAt;
    status: section_lFields.status;

}

export namespace section_mFields {
    export type id = number;
    export type courseId = number;
    export type accountId = number;
    export type title = string;
    export type createAt = number;
    export type status = number;

}

export interface section_m {
    id: section_mFields.id;
    courseId: section_mFields.courseId;
    accountId: section_mFields.accountId;
    title: section_mFields.title;
    createAt: section_mFields.createAt;
    status: section_mFields.status;

}

export namespace section_tFields {
    export type id = number;
    export type courseId = number;
    export type accountId = number;
    export type title = string;
    export type createAt = number;
    export type status = number;

}

export interface section_t {
    id: section_tFields.id;
    courseId: section_tFields.courseId;
    accountId: section_tFields.accountId;
    title: section_tFields.title;
    createAt: section_tFields.createAt;
    status: section_tFields.status;

}

export namespace sessionFields {
    export type id = string;
    export type accountId = number;
    export type expireAt = number;

}

export interface session {
    id: sessionFields.id;
    accountId: sessionFields.accountId;
    expireAt: sessionFields.expireAt;

}

export namespace session_lFields {
    export type id = string;
    export type accountId = number;
    export type expireAt = number;

}

export interface session_l {
    id: session_lFields.id;
    accountId: session_lFields.accountId;
    expireAt: session_lFields.expireAt;

}

export namespace session_mFields {
    export type id = string;
    export type accountId = number;
    export type expireAt = number;

}

export interface session_m {
    id: session_mFields.id;
    accountId: session_mFields.accountId;
    expireAt: session_mFields.expireAt;

}

export namespace session_tFields {
    export type id = string;
    export type accountId = number;
    export type expireAt = number;

}

export interface session_t {
    id: session_tFields.id;
    accountId: session_tFields.accountId;
    expireAt: session_tFields.expireAt;

}

export namespace videoFields {
    export type id = number;
    export type resource = string;
    export type recorder = string;
    export type accountId = number;
    export type status = number;

}

export interface video {
    id: videoFields.id;
    resource: videoFields.resource;
    recorder: videoFields.recorder;
    accountId: videoFields.accountId;
    status: videoFields.status;

}

export namespace video_lFields {
    export type id = number;
    export type resource = string;
    export type recorder = string;
    export type accountId = number;
    export type status = number;

}

export interface video_l {
    id: video_lFields.id;
    resource: video_lFields.resource;
    recorder: video_lFields.recorder;
    accountId: video_lFields.accountId;
    status: video_lFields.status;

}

export namespace video_mFields {
    export type id = number;
    export type resource = string;
    export type recorder = string;
    export type accountId = number;
    export type status = number;

}

export interface video_m {
    id: video_mFields.id;
    resource: video_mFields.resource;
    recorder: video_mFields.recorder;
    accountId: video_mFields.accountId;
    status: video_mFields.status;

}

export namespace video_tFields {
    export type id = number;
    export type resource = string;
    export type recorder = string;
    export type accountId = number;
    export type status = number;

}

export interface video_t {
    id: video_tFields.id;
    resource: video_tFields.resource;
    recorder: video_tFields.recorder;
    accountId: video_tFields.accountId;
    status: video_tFields.status;

}
