/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-01-17 12:50:14 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c mysql://username:password@localhost/moshi -t account -t account_role -t auth_code -t course -t permission -t role -t role_permission -t session -s moshi
 *
 */


export namespace accountFields {
    export type id = number;
    export type nickName = string;
    export type password = string;
    export type email = string;
    export type phone = string | null;
    export type avatar = string;
    export type realName = string | null;
    export type identityNumber = string | null;
    export type age = number | null;
    export type company = string | null;
    export type position = string | null;
    export type personalProfile = string | null;
    export type sex = string | null;
    export type birthday = number | null;
    export type education = string | null;
    export type profession = string | null;
    export type createAt = number;
    export type status = number;

}

export interface account {
    id: accountFields.id;
    nickName: accountFields.nickName;
    password: accountFields.password;
    email: accountFields.email;
    phone: accountFields.phone;
    avatar: accountFields.avatar;
    realName: accountFields.realName;
    identityNumber: accountFields.identityNumber;
    age: accountFields.age;
    company: accountFields.company;
    position: accountFields.position;
    personalProfile: accountFields.personalProfile;
    sex: accountFields.sex;
    birthday: accountFields.birthday;
    education: accountFields.education;
    profession: accountFields.profession;
    createAt: accountFields.createAt;
    status: accountFields.status;

}

export namespace account_roleFields {
    export type accountId = number;
    export type roleId = number;

}

export interface account_role {
    accountId: account_roleFields.accountId;
    roleId: account_roleFields.roleId;

}

export namespace auth_codeFields {
    export type id = string;
    export type accountId = number;
    export type expireAt = number;
    export type type = number;

}

export interface auth_code {
    id: auth_codeFields.id;
    accountId: auth_codeFields.accountId;
    expireAt: auth_codeFields.expireAt;
    type: auth_codeFields.type;

}

export namespace courseFields {
    export type id = number;
    export type accountId = number;
    export type columnName = string;
    export type profile = string;
    export type notice = string;
    export type createAt = number;
    export type publishAt = number | null;
    export type buyerCount = number;
    export type courseType = number;
    export type price = number;
    export type discountedPrice = number | null;
    export type offerTo = number | null;

}

export interface course {
    id: courseFields.id;
    accountId: courseFields.accountId;
    columnName: courseFields.columnName;
    profile: courseFields.profile;
    notice: courseFields.notice;
    createAt: courseFields.createAt;
    publishAt: courseFields.publishAt;
    buyerCount: courseFields.buyerCount;
    courseType: courseFields.courseType;
    price: courseFields.price;
    discountedPrice: courseFields.discountedPrice;
    offerTo: courseFields.offerTo;

}

export namespace permissionFields {
    export type id = number;
    export type actionKey = string;
    export type controller = string;
    export type remark = string | null;

}

export interface permission {
    id: permissionFields.id;
    actionKey: permissionFields.actionKey;
    controller: permissionFields.controller;
    remark: permissionFields.remark;

}

export namespace roleFields {
    export type id = number;
    export type name = string;

}

export interface role {
    id: roleFields.id;
    name: roleFields.name;

}

export namespace role_permissionFields {
    export type roleId = number;
    export type permissionId = number;

}

export interface role_permission {
    roleId: role_permissionFields.roleId;
    permissionId: role_permissionFields.permissionId;

}

export namespace sessionFields {
    export type id = string;
    export type accountId = number;
    export type expireAt = number;

}

export interface session {
    id: sessionFields.id;
    accountId: sessionFields.accountId;
    expireAt: sessionFields.expireAt;

}
